---
kind: Service
apiVersion: v1
metadata:
  name: node-exporter
#  namespace: monitoring
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '9100'
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer

  selector:
      app.kubernetes.io/component: exporter
      app.kubernetes.io/name: node-exporter
  ports:
  - name: node-exporter
    protocol: TCP
    port: 9100
    targetPort: 9100
 # loadBalancerIP: 10.13.117.121
