version: '3.7'
services:
  loki:
    image: grafana/loki:2.9.0
    ports:
      - "3100:3100"
    networks:
      - monitoring
    volumes:
      - loki_data:/dockerdata/loki
      - ./loki-config.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./k8s-config:/etc/prometheus/k8s-config
      - prometheus_data:/dockerdata/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - "9090:9090"
    networks:
      - monitoring
  grafana:
    image: grafana/grafana
    user: "472"
    depends_on:
      - prometheus
    ports:
      - 80:3000
    volumes:
      - grafana_data:/dockerdata/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./config.monitoring
    networks:
      - monitoring
    restart: always
networks:
  monitoring:
    driver: bridge
volumes:
  prometheus_data:
    driver: local
  grafana_data:
    driver: local
  loki_data:
    driver: local