apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: kube-state-metrics
    app.kubernetes.io/version: 2.3.0
  name: kube-state-metrics
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  namespace: default
spec:
  type: LoadBalancer

  ports:
  - name: http-metrics
    port: 8085
    targetPort: http-metrics
  - name: telemetry
    port: 8081
    targetPort: telemetry
  selector:
    app.kubernetes.io/name: kube-state-metrics
#  loadBalancerIP: 10.13.127.60
